// Package bootstrap embeds the Core plsnt skill set and materializes it into a
// target directory for a given agent app (Claude Code, Codex, Gemini CLI, etc.).
package bootstrap

import (
	"embed"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

//go:embed assets/skills
var skillsFS embed.FS

const skillsRoot = "assets/skills"

const (
	beginMarker = "<!-- BEGIN plsnt skills (auto-generated by `plsnt init`) -->"
	endMarker   = "<!-- END plsnt skills -->"
)

// Agent identifies the target agent app layout.
type Agent string

const (
	AgentClaude  Agent = "claude"
	AgentCodex   Agent = "codex"
	AgentGemini  Agent = "gemini"
	AgentGeneric Agent = "generic"
)

// ParseAgent converts a string into an Agent, erroring on unknown values.
func ParseAgent(s string) (Agent, error) {
	switch Agent(strings.ToLower(strings.TrimSpace(s))) {
	case AgentClaude:
		return AgentClaude, nil
	case AgentCodex:
		return AgentCodex, nil
	case AgentGemini:
		return AgentGemini, nil
	case AgentGeneric:
		return AgentGeneric, nil
	default:
		return "", fmt.Errorf("unknown agent %q (valid: claude, codex, gemini, generic)", s)
	}
}

// Skill is a single bundled skill loaded from the embedded filesystem.
type Skill struct {
	Name        string
	Description string
	Body        string // markdown body with frontmatter stripped
	Raw         string // full SKILL.md content
}

// Skills returns all embedded Core skills sorted by name.
func Skills() ([]Skill, error) {
	entries, err := skillsFS.ReadDir(skillsRoot)
	if err != nil {
		return nil, err
	}

	var skills []Skill
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		raw, err := skillsFS.ReadFile(filepath.ToSlash(filepath.Join(skillsRoot, e.Name(), "SKILL.md")))
		if err != nil {
			return nil, fmt.Errorf("read skill %q: %w", e.Name(), err)
		}
		name, desc, body := parseSkill(string(raw))
		if name == "" {
			name = e.Name()
		}
		skills = append(skills, Skill{
			Name:        name,
			Description: desc,
			Body:        body,
			Raw:         string(raw),
		})
	}

	sort.Slice(skills, func(i, j int) bool { return skills[i].Name < skills[j].Name })
	return skills, nil
}

// SkillNames returns the names of all embedded Core skills, sorted.
func SkillNames() ([]string, error) {
	skills, err := Skills()
	if err != nil {
		return nil, err
	}
	names := make([]string, len(skills))
	for i, s := range skills {
		names[i] = s.Name
	}
	return names, nil
}

// Install materializes the embedded skills into baseDir using the layout for
// the given agent. It returns the paths of the files written.
func Install(baseDir string, agent Agent) ([]string, error) {
	skills, err := Skills()
	if err != nil {
		return nil, err
	}

	if agent == AgentClaude {
		return installClaude(baseDir, skills)
	}
	return installMarkdownBundle(baseDir, agent, skills)
}

// installClaude writes each skill to <baseDir>/.claude/skills/<name>/SKILL.md.
func installClaude(baseDir string, skills []Skill) ([]string, error) {
	var written []string
	for _, s := range skills {
		dir := filepath.Join(baseDir, ".claude", "skills", s.Name)
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return written, err
		}
		path := filepath.Join(dir, "SKILL.md")
		if err := os.WriteFile(path, []byte(s.Raw), 0o644); err != nil {
			return written, err
		}
		written = append(written, path)
	}
	return written, nil
}

// installMarkdownBundle writes a single concatenated file (AGENTS.md or
// GEMINI.md), merging into existing user content via begin/end markers so that
// re-running init is idempotent and never clobbers user-authored sections.
func installMarkdownBundle(baseDir string, agent Agent, skills []Skill) ([]string, error) {
	target := "AGENTS.md"
	if agent == AgentGemini {
		target = "GEMINI.md"
	}
	path := filepath.Join(baseDir, target)

	block := renderBundle(skills)

	existing, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return nil, err
	}
	merged := mergeBlock(string(existing), block)

	if err := os.MkdirAll(baseDir, 0o755); err != nil {
		return nil, err
	}
	if err := os.WriteFile(path, []byte(merged), 0o644); err != nil {
		return nil, err
	}
	return []string{path}, nil
}

// renderBundle builds the marker-delimited plsnt skills block.
func renderBundle(skills []Skill) string {
	var b strings.Builder
	b.WriteString(beginMarker)
	b.WriteString("\n# plsnt skills\n\n")
	b.WriteString("These reference patterns describe how to operate the `plsnt` CLI. " +
		"Any agent can use them as long as `plsnt` is on PATH.\n\n")
	for _, s := range skills {
		fmt.Fprintf(&b, "## %s\n\n", s.Name)
		if s.Description != "" {
			fmt.Fprintf(&b, "%s\n\n", s.Description)
		}
		b.WriteString(strings.TrimSpace(s.Body))
		b.WriteString("\n\n")
	}
	b.WriteString(endMarker)
	b.WriteString("\n")
	return b.String()
}

// mergeBlock replaces an existing marker-delimited block, or appends a new one
// while preserving any surrounding user content.
func mergeBlock(existing, block string) string {
	existing = strings.TrimRight(existing, "\n")
	if existing == "" {
		return block
	}

	start := strings.Index(existing, beginMarker)
	end := strings.Index(existing, endMarker)
	if start >= 0 && end > start {
		before := strings.TrimRight(existing[:start], "\n")
		after := strings.TrimLeft(existing[end+len(endMarker):], "\n")
		var b strings.Builder
		if before != "" {
			b.WriteString(before)
			b.WriteString("\n\n")
		}
		b.WriteString(block)
		if after != "" {
			b.WriteString("\n")
			b.WriteString(after)
			b.WriteString("\n")
		}
		return b.String()
	}

	return existing + "\n\n" + block
}

// parseSkill extracts name, description, and the body (frontmatter stripped)
// from a SKILL.md file. Frontmatter is a leading "---" delimited block with
// simple single-line "key: value" entries.
func parseSkill(raw string) (name, description, body string) {
	rest := raw
	if strings.HasPrefix(raw, "---") {
		// Find the closing delimiter line.
		lines := strings.Split(raw, "\n")
		closeIdx := -1
		for i := 1; i < len(lines); i++ {
			if strings.TrimSpace(lines[i]) == "---" {
				closeIdx = i
				break
			}
		}
		if closeIdx > 0 {
			for _, l := range lines[1:closeIdx] {
				if k, v, ok := strings.Cut(l, ":"); ok {
					key := strings.TrimSpace(k)
					val := strings.TrimSpace(v)
					switch key {
					case "name":
						name = val
					case "description":
						description = val
					}
				}
			}
			rest = strings.Join(lines[closeIdx+1:], "\n")
		}
	}
	return name, description, strings.TrimLeft(rest, "\n")
}
